Add ability to verify audience contains at least one of those expected
auth0/java-jwt pull request #472
Opened 2021-02-02 00:21 UTC by jimmyjames

### Changes

This PR adds the ability to verify that a JWT's audience claim contains at least one of the expected audiences. Currently, `withAudience` requires that the audience claim match the specified audience exactly.

Resolves #449

**New public method:**

- `withAnyOfAudience(String... audience)` - verifies that the JWT's audience claim contains at least one of the specified audiences.

**Details:**

- If both `withAudience` and `withAnyOfAudience` are called on the same `Verification` instance, an `IllegalStateException` will be thrown.

**Alternatives considered:**

- Instead of managing the audience verification behavior with an enum, we could instead keep a boolean flag. This would mean that if both `withAudience` and `withAnyOfAudience` are used on the same `Verification` instance, the last one called wins. We could document that behavior, but discussion with @lbalmaceda thought it best for us to throw in that scenario.

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

2021-02-02 10:29 UTC, lbalmaceda requested changes
I think we can avoid this flag if we reuse the existing `Map<String, Object> claims`. We could define a new constant for `AUDIENCE_EXACT` vs `AUDIENCE_CONTAINS` and then in the switch case pick the strategy. 

https://github.com/auth0/java-jwt/blob/5afd80d3340857975afdc2dac46f5d2fe5b2ec82/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L326-L331

The only thing I'd be careful of is not exposing these two new constants, as they are rather used internally.

The flag would go away and we could even skip checking and throwing if a different audience verification strategy was already set, as both could now co-exist. Thoughts?

2021-02-02 20:46 UTC, jimmyjames commented on lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
> +     * An {@linkplain IllegalStateException} will be thrown if this Verification instance has already been
We do, see the JavaDoc for `withAnyOfAudience` below.

2021-02-03 01:31 UTC, jimmyjames commented
> I think we can avoid this flag if we reuse the existing `Map<String, Object> claims`. We could define a new constant for `AUDIENCE_EXACT` vs `AUDIENCE_CONTAINS` and then in the switch case pick the strategy.
> 
> https://github.com/auth0/java-jwt/blob/5afd80d3340857975afdc2dac46f5d2fe5b2ec82/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L326-L331

Yes, we could do that. It avoids adding another parameter to the `JWTVerifier` constructor, which is good. However, I do wonder if it makes the code a bit more confusing, as we'd be using non-standard claim keys for the different audience verification strategies. It's an internally managed map of the expected values, but I could see that causing some confusion for future maintainers. It's a trade-off, no additional constructor param or using non-standard claim keys in the internal verification logic.

> The flag would go away and we could even skip checking and throwing if a different audience verification strategy was already set, as both could now co-exist. Thoughts?

Can you think of a use case where both strategies would be used on the same verification? Or, we don't need to throw an exception if both are used, and instead could let the last one configured win. If using new custom claim keys to determine how the audience should be validated, we'd just remove the other claim from the expectations (e.g., `withAudience` would first remove any claim entries with the `AUDIENCE_CONTAINS` key).

2021-02-03 16:45 UTC, jimmyjames commented
> Yes, we could do that. It avoids adding another parameter to the `JWTVerifier` constructor, which is good. However, I do wonder if it makes the code a bit more confusing, as we'd be using non-standard claim keys for the different audience verification strategies. It's an internally managed map of the expected values, but I could see that causing some confusion for future maintainers. It's a trade-off, no additional constructor param or using non-standard claim keys in the internal verification logic.
> 
> > The flag would go away and we could even skip checking and throwing if a different audience verification strategy was already set, as both could now co-exist. Thoughts?
> 
> Can you think of a use case where both strategies would be used on the same verification? Or, we don't need to throw an exception if both are used, and instead could let the last one configured win. If using new custom claim keys to determine how the audience should be validated, we'd just remove the other claim from the expectations (e.g., `withAudience` would first remove any claim entries with the `AUDIENCE_CONTAINS` key).

We discussed offline, and will proceed to manage the expected audience values internally using different keys for the desired verification behavior. We will also update this PR such that if both `withAudience` and `withAnyAudience` are used on the same `Verification` instance, the audience verification behavior will be overridden (last one wins).

2021-02-04 15:23 UTC, lbalmaceda approved these changes

2021-02-05 16:03 UTC, lbalmaceda approved these changes

2021-02-05 16:03 UTC, merged