[SDK-3694] README redesign
auth0/java-jwt pull request #617
Opened 2022-10-15 01:46 UTC by jimmyjames

Updates the README per the new design.

- This PR does not include the new banner; will follow-up with that once design is available.
- I moved quite a bit of the content in the README to a new EXAMPLES file
- Some of the info in the README was basically API-level documentation. I removed that, as the linked-to javadocs contain that information.

2022-10-17 08:41 UTC, frederikprijck requested changes

2022-10-17 08:41 UTC, frederikprijck commented on README.md
> +- [Examples](./EXAMPLES.md) - code samples for common auth0-java scenarios.
```suggestion
- [Examples](./EXAMPLES.md) - code samples for common java-jwt scenarios.
```

2022-10-17 08:41 UTC, frederikprijck commented on README.md
> +[![javadoc](https://javadoc.io/badge2/com.auth0/auth0/javadoc.svg)](https://javadoc.io/doc/com.auth0/java-jwt)
Should this be java-jwt ?

```suggestion
[![javadoc](https://javadoc.io/badge2/com.auth0/java-jwt/javadoc.svg)](https://javadoc.io/doc/com.auth0/java-jwt)
```

2022-10-17 08:41 UTC, frederikprijck commented on README.md
> +> `auth0-java` is intended for server-side JVM applications. Android applications should use the [Auth0.Android SDK](https://github.com/auth0/auth0.android).
Is this reference to `auth0-java` intentional?

2022-10-17 14:00 UTC, jimmyjames commented on README.md
> +- [Examples](./EXAMPLES.md) - code samples for common auth0-java scenarios.
pushed new commit to fix.

2022-10-17 14:01 UTC, jimmyjames commented on README.md
> +[![javadoc](https://javadoc.io/badge2/com.auth0/auth0/javadoc.svg)](https://javadoc.io/doc/com.auth0/java-jwt)
pushed new commit to fix.

2022-10-17 14:01 UTC, jimmyjames commented on README.md
> +> `auth0-java` is intended for server-side JVM applications. Android applications should use the [Auth0.Android SDK](https://github.com/auth0/auth0.android).
No, should be java-jwt. Pushed new commit to fix.

2022-10-17 14:12 UTC, frederikprijck submitted a review, later dismissed

2022-10-24 15:09 UTC, frederikprijck approved these changes

2022-10-25 08:54 UTC, frederikprijck submitted a review, later dismissed

2022-10-26 07:09 UTC, frederikprijck approved these changes

2022-10-26 08:38 UTC, merged